### ISSUE TITLE
humidity over 100% indicates error; display of humidity should be suppressed

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#26] opened 2019-09-30 23:50 UTC
Most recent version of firmware i.e. 2.5.7 will report 120% if compensated value from humidity sensor returns a value greater than 120%.
```
( // Cap maximum reported value to 120% 
 	v_x1_u32r = (v_x1_u32r > 503316480 ? 503316480 : v_x1_u32r);
```
//note that 503316480 is 120 shifted left 12 then 10 bits for a return in 22.10 fixed point integer format
Actually any value over 100% (was 99% )is incorrect.
I would like to suggest either:
1) Suppress / dim display of humidity when value received is >100% (was 99% )

10/29/19 delete the falling phrase: xxx really 100% doesn't even make sense and thatxxx

 was a previous value returned if value was greater than 100%)

10/29/19 delete  XXX 2) Display the previous value XXX

**Comment by rinat-enikeev** [comment] 2019-10-29 17:59
nice! will do something beautiful.

**Comment by DG12** [comment] 2019-10-29 18:06
Actually, in my experience, BME280 sensor reporting over 100% are just wrong! 
Even recent and subsequent values are also wrong. 
Not correctable by a  liner calibration factor.
I can provide some data demonstrating this if you like.

**Comment by DG12** [comment] 2019-10-29 18:25
Values in my attic which I have confirmed with another instrument as being much less than 90% can be seen here:

http://dalogger.dns04.com:8888/sources/1/dashboards/11?lower=2019-09-01T18%3A13%3A00.000Z&upper=2019-10-01T18%3A13%3A00.000Z

As I have recently received a tag with the SHTC3 I will move it to be adjacent  to DC4B596ED18B for future comparison.

**Comment by rinat-enikeev** [comment] 2019-11-18 16:19
@DG12 can you reproduce the issue with 0.4(30) build?

**Comment by DG12** [comment] 2019-11-18 23:09
You asked.
<img width="915" alt="Ruuvi100H-EC0F-fmt03" src="https://user-images.githubusercontent.com/2365961/69074812-18c30a80-09fe-11ea-9288-5379796539c5.png">

![Ruuvi100H-ECoF-IOS](https://user-images.githubusercontent.com/2365961/69075212-eebe1800-09fe-11ea-99a1-202cf0abef11.jpeg)
++++++++++++
Flashed the TAG with 3.28.0  now interestingly:

![Ruuvi100H-ECoF-IOSwithALert](https://user-images.githubusercontent.com/2365961/69078656-5330a580-0a06-11ea-9c68-c5f32794444d.jpeg)

Blinking alert symbol now **brings attention** to incorrect value ! 
IMHO not the right idea, as I suggested suppressing it altogether or dim seems better to me!

Actually I would interpret this alert symbol to indicate that the location at the tag is underwater!!

++++++++++++
Nearby tag(D250) with SCHT3 reports a more accurate 88.22% ( Bosch responded to a query of mine "absolute accuracy is also +/-3%RH from 80%RH ~ 90%RH range +/-**6%**RH from 90%RH ~ 100%RH." )



+++++++++++++
BUT WAIT!! 

Now this same tag, after an initial slam up to 160%(!?) and a crash to 0.04%  and a 2 HOUR adjustment period it is now reporting a reasonable 83% !!

<img width="1096" alt="RuuviEC0F-firmewareUpgrade" src="https://user-images.githubusercontent.com/2365961/69101646-2bedce80-0a2e-11ea-9f04-bf6671621a86.png">

If you wish to see the data yourself check it out at [DG12sRuuvis](http://DaLogger.DNS04.com:8888)

**Comment by ojousima** [comment] 2019-11-20 10:08
I think the core issue is in untrusted data from sensor which produces faulty readings. The mobile app has no way of knowing what the real source of the data is, it could be RuuviTag with BME280, SHTC3 or it could be a specialized instrument broadcasting in Ruuvi format. 

Your last image is interesting @DG12 , it looks like that sensor sent NOT AVAILABLE data for a moment, and Grafana is averaging it with other measurements. Maybe the fixed data indicates a poor connection inside BME280 which ends up getting restored? 

The responsibility for detecting and reporting faulty sensor lies on the peripheral sensor side, app must assume that it is fed correct data. UI wise showing an alert when humidity is at 100% or above is reasonable action, as it indicates that tag has condensation moisture.

**Comment by rinat-enikeev** [comment] 2020-11-15 14:58
should be fixed, @viikufa could you please take a look?

**Comment by rinat-enikeev** [comment] 2021-05-27 08:10
@DG12 we've added sensor offset calibration in the 0.7(73) build. We've done the alert icon. Is this issue still relevant?

**Comment by DG12** [comment] 2021-05-29 04:08
I will check to see if this is still an issue. Pouring rain right now. I will post additional information or closed this issue.

**Comment by markoaamunkajo** [comment] 2021-05-31 14:05
Thanks!

**Comment by rinat-enikeev** [comment] 2021-06-09 07:34
closing it for now, please feel free to reopen with steps to reproduce and additional details.

**Closed by rinat-enikeev** 2021-06-09 07:34 UTC
