### ISSUE TITLE
RSSI shows for a second then blanks -

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2069] opened 2024-07-01 03:20 UTC
See attached video

https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/4bd795fd-7fce-487c-953a-6091cc2adc2c

**Comment by markoaamunkajo** [comment] 2024-07-04 04:05
@DG12 Are you checking this sensor in Cloud mode or Bluetooth? Is the sensor closeby and is it possibly running long life firmware?

**Comment by DG12** [comment] 2024-07-04 17:13
Sorry, I didn't think (full stop) that this was sensor specific. Especial since RSSI is determined by the app.

Related to whether the data from the sensor was received by heartbeat (bad) or advertisement(good)!

Ruuvi 3B86 running RuuviFW v3.31.1+default.
App is 240702 2051 
Additional observation: 
98% of the time the app shows Data Received by Heartbeat with RSSI null
2% of the time it shows RSSI AND Data Received by Advertisment

For Ruuvi 20BC & Ruuvi 22AB app seems to only receive data via heartbeat and app does not show RSSI

For Ruuvi AD03 & 24C2 only receives advertisement and always shows RSSI

Sensors running older firmware only transmit advertisements while current firmware ONLY(?) transmit heartbeat.

**Comment by markoaamunkajo** [comment] 2024-07-05 02:04
This is the behaviour, I reproduced it without sign in, Bluetooth sensor and pairing is on.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/989745e7-4d71-48d8-b907-0faa1b9b612d

**Comment by markoaamunkajo** [comment] 2024-07-23 07:08
This can also be observed on logs when pairing sensor.

[RuuviTag B8_Connected_20240723T103824+0700.csv](https://github.com/user-attachments/files/16344956/RuuviTag.B8_Connected_20240723T103824%2B0700.csv)

**Comment by priyonto** [comment] 2024-08-01 16:22
@markoaamunkajo Yes, RSSI value is not available when sensor is paired. That's when sensor is paired we don't show RSSI value. And because in some cases (paired) connection is not stable app goes back to advertisement mode, and then it gets RSSI value which makes the app flip between proper and empty value.

**Comment by markoaamunkajo** [comment] 2024-08-02 03:36
@DG12 this is by design. Nothing to do on the card so closing this.

**Closed by markoaamunkajo** 2024-08-02 03:36 UTC
Labels: bug
