### ISSUE TITLE
Implement push notification

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1211] opened 2023-01-19 21:23 UTC

**Comment by markoaamunkajo** [comment] 2023-02-13 05:19
@priyonto need instructions on how to confirm

**Comment by markoaamunkajo** [comment] 2023-02-14 03:08
Discussed reason for multiple push notifications received within the first 1 hour duration (occurred because I was adjusting threshold and it triggered). Not caused by app, closing this issue.

**Closed by markoaamunkajo** 2023-02-14 03:08 UTC
Labels: high priority
