### ISSUE TITLE
Already shared {1^1d}/{10^20d} - 0.7.7 (236)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#701] opened 2022-01-21 21:27 UTC
After sharing displays 
<pre>Already shared {1^1d}/{10^20d}</pre>

**Comment by priyonto** [comment] 2022-02-02 13:57
This is a duplicate of #705  and it's fixed on 0.7.7(243)

**Closed by priyonto** 2022-02-02 13:57 UTC
