### ISSUE TITLE
Tags not seen recently report last humidity *.01 (example reported as 0.51% SB 51%)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#96] opened 2020-07-06 00:23 UTC
When a data has not been received from a tag for a long(?) time the humidity is reported as one hundredth of what it was.

**Comment by DG12** [comment] 2020-07-09 22:19
This also occurs the first time data is presented for a new tag.

**Comment by rinat-enikeev** [comment] 2020-11-15 14:48
what build number?

**Comment by DG12** [comment] 2020-11-15 23:44
Now I've got one that shows 1.3% with an active tag !!
build 0.6.1(18)
![RuuviTagWrongHumidityDisplay](https://user-images.githubusercontent.com/2365961/99200204-e9aaba80-2771-11eb-91f5-7852abc03451.jpeg)

influx 
select mac,ceil(temperature*9/5)+32,humidity from ruuvi_measurements where time > now() -2m group by mac tz('America/New_York')

name: ruuvi_measurements
tags: mac=D3517872EC0F
time                mac          ceil humidity
----                ---          ---- --------
1605483678813569199 D3517872EC0F 65   129.1575

**Comment by DG12** [comment] 2020-11-15 23:49
Actually this is a case of #26   OOPS

**Comment by rinat-enikeev** [comment] 2021-05-27 08:21
closed as duplicate of #26

**Closed by rinat-enikeev** 2021-05-27 08:21 UTC
