### ISSUE TITLE
0.7(70) Sensor calibration data not synced to and from network

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#304] opened 2021-05-24 14:50 UTC
Description:

User sets calibration settings for 2 sensors that are connected to network, then syncs network and after that uninstalls and reinstalls app.

Actual: Offset calibration is not downloaded from network.
Expected: Offset calibration should be synced to and from network.

**Comment by andreevdenis** [comment] 2021-05-24 14:58
See task #284

**Comment by rinat-enikeev** [comment] 2021-05-25 11:10
closing this (duplicate of #284)

**Closed by rinat-enikeev** 2021-05-25 11:10 UTC
Labels: bug
