### ISSUE TITLE
Sync should report first, last and number of entries - enhancment - 0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#47] opened 2020-01-21 15:44 UTC
Sync needs to be more talkative.
Currently 0.5(16) only reports:"connecting, syncing" quickly. (or not)
It should report progress as it goes.
On completion should report number of entries received, time of first and last and wait for acknowledgment.

**Comment by rinat-enikeev** [comment] 2020-11-15 14:55
unreachable, idk from start how long will it take to download all data

**Comment by DG12** [comment] 2020-12-23 22:04
Nice would be  something like 
100,200,300 ...

**Comment by rinat-enikeev** [comment] 2021-06-09 08:36
closing as duplicate of https://github.com/ruuvi/com.ruuvi.station.ios/issues/317

**Closed by rinat-enikeev** 2021-06-09 08:36 UTC
