### ISSUE TITLE
Claim Ownership blinks  Unexpected HTTP status code - defect -240730 2019

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2106] opened 2024-08-02 00:56 UTC
I have C1:9A:0B:19:3B:B6.
I wanted to share it but says no owner.
Tap Claim Ownership, blinks "[X] Unexpected HTTP status code"

https://github.com/user-attachments/assets/5d23e32c-092f-417c-9c17-a05d42a48775

AWWW it's a QT movie.

![image](https://github.com/user-attachments/assets/3bebf050-4d52-40dd-bc43-5a81668b5f4b)

<img width="408" alt="unexpecteed2of2" src="https://github.com/user-attachments/assets/df5e404c-6f86-4c68-99f9-4338e3d5949e">

**Comment by markoaamunkajo** [comment] 2024-08-02 01:01
@DG12 thanks for reporting this. Do you have any issue with other Cloud features? This seems like Cloud or internet connection related, will test this asap.

**Comment by markoaamunkajo** [comment] 2024-08-02 05:23
I cannot reproduce this on my sensors at this moment, spent some time testing different scenarios.

**Comment by markoaamunkajo** [comment] 2024-08-02 07:58
Discussed in meeting and @priyonto said he might have some ideas, moving card to him.

**Comment by priyonto** [comment] 2024-08-12 16:47
@DG12 Fixed the error message to show the correct message. I am unsure what is the root cause of failed claim. On next build please try again and see if you get error and which error.

**Comment by markoaamunkajo** [comment] 2024-08-13 04:43
This is not seen in my case, so closing this card, hoping that it's not shown again.

**Closed by markoaamunkajo** 2024-08-13 04:43 UTC
Labels: bug
