### ISSUE TITLE
0.7.2(116) Gatt sync synchronizing text showing on all sensor chart pages

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#506] opened 2021-07-13 13:21 UTC
Description:

Synchronizing.... text is showing on all chart pages if user is GATT syncing one sensor.
Is it to prevent user to syncing multiple sensors at same time or should it be fixed?

**Comment by markoaamunkajo** [comment] 2021-07-13 13:22
Easy way to check this is start gatt sync, remove battery, visit other chart pages

**Comment by DG12** [comment] 2021-07-13 15:10
Or walk out of range?

**Comment by priyonto** [comment] 2022-01-26 09:22
This is a duplicate of #643. I am closing this one.

**Closed by priyonto** 2022-01-26 09:22 UTC
Labels: bug
