### ISSUE TITLE
Tag Name should not be truncated on main screen (it is OK on chart screen)  -0.6.2(4) minor defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#147] opened 2020-11-16 04:29 UTC
Tag name should be allow to be as wide as screen permits (even if it is necessary to hold in landscape mode)
Tag named 
Ruuvi 22AB was SWAMP shows as 
Ruuvi 22AB was SWA... on main screen
![RuuviwasSwa](https://user-images.githubusercontent.com/2365961/99212900-3dc99500-279a-11eb-8777-872a33fe5013.jpeg)
![RuuviwasSwa](https://user-images.githubusercontent.com/2365961/99213076-a87ad080-279a-11eb-931a-15b030f933ba.jpeg)

**Comment by rinat-enikeev** [comment] 2021-06-09 08:34
let's do multiple lines `UILabel`

**Comment by priyonto** [comment] 2022-01-11 10:54
This is a duplicate of #662.

**Closed by priyonto** 2022-01-11 10:54 UTC
