### ISSUE TITLE
Feedback cannot be sent

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#794] opened 2022-03-16 01:18 UTC
User report (0.7.7 255):

![image](https://user-images.githubusercontent.com/1311912/158497041-a105d63c-7cc8-47f3-8739-29d6f5ee4d1c.png)

I tried the same build with my iPhone SE (iOS 15.3.1):

First what happened was this:

![image](https://user-images.githubusercontent.com/1311912/158497443-ba318301-9a47-4b74-a405-4e312d5ab3cc.png)

Then I installed Gmail and logged in and checked that Gmail is configured as the default email client:

![image](https://user-images.githubusercontent.com/1311912/158497514-e60e684a-5ae6-417c-83cf-2e2a8849d2b1.png)

But no help. Still getting the same message "Restore "Mail"?". Even a phone reboot didn't fix this situation. Still it wants me to restore the Mail app and not letting me to send feedback using the default email app (Gmail).

**Comment by markoaamunkajo** [comment] 2022-03-21 02:10
0.7.7(257), ios 15.4.

Looks like Apple has really missed the boat on this one...
Steps:
1. Delete Mail app (because why not)
2. Open Ruuvi Station, Send Feedback
3. Popup shown

![IMG_2863](https://user-images.githubusercontent.com/50437378/159196938-77cd25fd-d8a5-4b07-9bcf-882c3b61aa45.PNG)

**Comment by priyonto** [comment] 2022-03-21 07:39
@markoaamunkajo 
Hmm. Surprisingly I can't reproduce this on my device. Did you select any default mail app on the settings after deleting the Mail app? Something like this?
![IMG_1CFAB2262F2F-1](https://user-images.githubusercontent.com/24395776/159220653-13320700-e745-495d-b9ed-d4b41521f838.jpeg)

**Comment by laurijamsa** [comment] 2022-03-21 07:48
I also see Gmail as a default mail app in the settings like told in the previous message. Here's another screenshot of it:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1311912/159221583-4a95ce49-9727-4056-a978-9a9566520cf2.png">

**Comment by priyonto** [comment] 2022-03-21 08:20
@laurijamsa Thanks. Would you please try 257 if you have some time? In my device I can't reproduce it. 
iOS 15.4, iPhone 11 Pro Max

**Comment by markoaamunkajo** [comment] 2022-03-21 08:27
@priyonto Would you believe if I told you I don't have such setting... 

![IMG_2869](https://user-images.githubusercontent.com/50437378/159226216-91c855b8-31c7-4b42-8758-469f5c7fca14.PNG)
![IMG_B64E5BCE90C7-1](https://user-images.githubusercontent.com/50437378/159226229-b4f03a70-cb94-43c5-92cd-5e993651730a.jpeg)

**Comment by priyonto** [comment] 2022-03-21 08:30
I get it. That's the reason you are seeing the Mail app popup because setting app "Default" mail app is not supported on your device!!! What device you are on?

**Comment by markoaamunkajo** [comment] 2022-03-21 08:33
@priyonto iPhone 6 Plus

**Comment by priyonto** [comment] 2022-03-21 08:36
> @priyonto iPhone 6 Plus

iPhone 6 Plus is not compatible with iOS 13 or above. The default email app setting is available for iOS 14 and above. Devices with iOS 13 or less must have Mail app installed to open email link.

**Comment by priyonto** [comment] 2022-03-21 08:37
@markoaamunkajo 
I think you mentioned you are on iOS 15.4! How are you on iOS 15.4 with iPhone 6 Plus? Or it is 6s Plus?

**Comment by markoaamunkajo** [comment] 2022-03-21 08:39
You are right it's actually 6s Plus @priyonto

**Comment by priyonto** [comment] 2022-03-21 08:45
@markoaamunkajo Then it should show the Default Mail App setting automatically. I am not sure whether it is device-specific or anything but as far I knew it should be available on devices with iOS 14 and above.

**Comment by markoaamunkajo** [comment] 2022-03-21 08:46
@priyonto yes I see the setting on my iPhone 7 and iOS 14.8

**Comment by priyonto** [comment] 2022-03-21 08:49
> @priyonto yes I see the setting on my iPhone 7 and iOS 14.8 I see this must be OS specific issue nothing we can do here.

I believe so. But, is the default mail app opening when you tap feedback on your iPhone 7?

**Comment by markoaamunkajo** [comment] 2022-03-21 08:56
@priyonto Gmail is selected as default mail app:
![feedback_iPhone7](https://user-images.githubusercontent.com/50437378/159230107-699bf05a-304e-43aa-8399-2183484a9314.jpg)

**Comment by priyonto** [comment] 2022-03-21 08:58
@markoaamunkajo Are you checking on the test flight version? This is fixed on build 257, not TF.

**Comment by markoaamunkajo** [comment] 2022-03-21 09:01
@priyonto Ah my bad yes I see it's working correctly on correct version and iPhone7

**Comment by priyonto** [comment] 2022-03-21 09:26
> @priyonto Ah my bad yes I see it's working correctly on correct version and iPhone7

Then I think we can close this one? 
The point to note is - devices with no default mail app settings will always open the iOS default mail app if it's installed, if not then will show that popup.

**Comment by markoaamunkajo** [comment] 2022-03-21 09:27
Closing

**Closed by markoaamunkajo** 2022-03-21 09:27 UTC
Labels: bug
