### ISSUE TITLE
In claim sensor pop-up verify ownership button not visible on iPhone SE.

### ISSUE THREAD

**Issue by hakunti** [ruuvi/com.ruuvi.station.ios#602] opened 2021-10-27 11:45 UTC

**Comment by markoaamunkajo** [comment] 2021-11-01 14:26
Cannot reproduce on iPhone 7 with larger font used, this is likely SE specific.

**Comment by andreevdenis** [comment] 2021-11-01 14:28
Can confirm for SE while Finnish language selected. With English language button stays clickable.

**Comment by markoaamunkajo** [comment] 2021-11-01 14:30
Thanks for the help @andreevdenis !

**Comment by markoaamunkajo** [comment] 2021-12-13 01:31
@andreevdenis could you help rechecking this issue?

**Comment by andreevdenis** [comment] 2021-12-13 10:29
@markoaamunkajo not fixed in 214.

**Comment by Iikeli** [comment] 2021-12-13 11:48
@markoaamunkajo @andreevdenis new build in firebase now.

**Comment by Iikeli** [comment] 2021-12-16 16:32
@markoaamunkajo @andreevdenis can you re check this? The fix should now be in the firebase build.

**Comment by andreevdenis** [comment] 2021-12-16 17:09
Button is fully operational. But can't scroll deep enough to see full last string in description.

![IMG_20211216_200745_135.jpg](https://user-images.githubusercontent.com/24788772/146416808-b586f795-c6d2-4906-8ea0-638701b776d4.jpg)

**Comment by Iikeli** [comment] 2021-12-17 10:43
@andreevdenis fixed the truncation mode and added some extra spacing between the button and text. Could you check again with the new Firebase build?

**Comment by andreevdenis** [comment] 2021-12-17 15:45
224:

https://user-images.githubusercontent.com/24788772/146570571-da54dcb0-3a7f-4bb1-bdbf-abfde520977f.mp4

**Comment by andreevdenis** [comment] 2021-12-17 15:50
Button text should be "Vahvista Omistajuus". Maybe setting smaller inner padding for button will help?

**Comment by laurijamsa** [comment] 2021-12-20 10:10
Build with this partial fix is available in TestFlight. Let's fix it better and then release asap to TestFlight and Production. Moving to In Progress.

**Comment by markoaamunkajo** [comment] 2022-01-14 03:29
@andreevdenis could you check with your iPhone SE?

**Comment by andreevdenis** [comment] 2022-01-14 10:44
Everything is good now

**Closed by andreevdenis** 2022-01-14 10:44 UTC
Labels: bug, good first issue, 1d
