### ISSUE TITLE
After aborting synchronization   sync again completes instantly without data 2.2.0(376) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1109] opened 2022-10-25 00:56 UTC
Attempt to sync to 450A in the swamp.
RSSI very low. -99 to -96 ( No I cannot get any closer it's flooded)
see previous photos at [MyBeacons.info/swampFlood](http://mybeacons.info/swampFlood.html)

Get advertisements only every every 2-3 minutes,
Tap sync. App reports synchronizing but nothing further.
Presents cancel Botton which I tapped on.

At this point issuing another sync completes instantly.

Tapping clear then sync works,  of course previous data is unretrievable.

**Comment by markoaamunkajo** [comment] 2022-12-11 12:41
This works for me correctly, my sensor is in about -91dB even a bit lower.
Closing this issue for now, feel free to reopen if this occurs in latest build for you.

**Comment by DG12** [comment] 2022-12-11 13:32
It seems if the sync is aborted while active, sync again is OK.
If sync stalls and is then canceled, it seems that  _something like_ **timestampOfLastDataSynced**  gets set to NOW.

**Comment by DG12** [comment] 2023-06-09 22:04
Please reopen.
After a sync aborts,. either by user tapping X or after transferring some data and getting stuck, user immediately retries sync. Connect, synchronize, returns immediately as if all data was transferred but no data is transferred.

Perhaps "timestamp_of_last_sync" gets set at the beginning of the sync??
or maybe after the sync exits "timestamp_of_last_sync" gets set without checking if sync completed sucessfully??

**Comment by laurijamsa** [comment] 2023-06-10 05:32
Reopening for @markoaamunkajo to check

**Comment by markoaamunkajo** [comment] 2023-08-07 06:29
Any ideas @priyonto ?

**Comment by priyonto** [comment] 2023-08-07 07:25
Yeah, needs checking the code. Were you able to reproduce the issue tho?

**Comment by markoaamunkajo** [comment] 2023-08-07 07:27
Not on my side unfortunately.

**Comment by priyonto** [comment] 2023-08-07 07:29
Me neither. I will double check the code and write back.

**Comment by DG12** [comment] 2023-08-12 01:38
Still occurs with 2.3.0(393)
Not actually dependent on RSSI value, 
but occurs when signal is good enough to connect and begin synchronization but then gets gets stuck. 
Uploaded version (393) and start all over again. Logged on, disconnect, then added 230E, received a some advertisements then taped sync. 
After Reading Bluetooth: 167 packets, station got stuck. User taps X and aborts download. 

Next tapping Sync says, connecting, synchronizing,.. sync "completes" without transferring any data.

RSSI at iPhone happens to vary between -92 and -86

**Comment by priyonto** [comment] 2023-08-14 19:50
I managed to reproduce it and put a potential fix on build 398. 

One note: After aborting sync, tag takes a minutes or so to get back to regular advertising state. At that period sensor does not update with regyuar interval of 1/2 seconds.

**Comment by markoaamunkajo** [comment] 2023-08-15 10:25
Moving this to beta build, @DG12 please check if it works for you when beta is out.

**Closed by markoaamunkajo** 2023-08-15 10:25 UTC
Labels: bug, investigation

**Comment by DG12** [comment] 2023-08-15 22:37
Installed 378. ( Did not ask to delete app and data)
Only one sensor present 230E (as expected)
Let advertisements collect 12:47:15 until (at least  12:49:46, as per export)
check RSSI to iPhone -87,-89,-88,-80,-92,-80,-94,-81..
Tsp sync: connecting, synchronizing, reading bluetooth ...,.,,.,,,.,,,
      stuck at 513
Advertisements still being received every 1,5,7,2,3,2,1,3 seconds.

Chart covers 22:48 to 12:54
tap X to stop download. tap ABORT download.
chart covers 12:48 to 12:56
export : last 2 entries:
```
2023-08-15 12:56:42,74.98,100.00,993.04,-84,0.032,-0.024,0.992,2.152,75,17088,4
2023-08-15 12:56:45,74.98,100.00,993.04,-89,0.032,-0.016,0.996,2.152,75,17090,4
```
All rows include all columns i.e. not from history.

tap sync
connecting , sync, reading..,., stuck at 386.
tap X to abort
export :
```
2023-08-15 13:00:03,75.01,100.00,993.06,-86,0.036,-0.016,0.992,2.204,75,17164,4
2023-08-15 13:00:05,75.01,100.00,993.06,-90,0.032,-0.016,0.992,2.204,75,17165,4
```
i.e. no history data has been added.  :-(
sync ,connecting, sync, reading ..., stuck at 364
**At least it seems NOT to be starting at time of last sync attempt.**
tap X to abort.

Moving close to sensor.
+++++++++++++++++++++++
RSSI now in the -32 to -35 range.
tap sync, connect, sync,reading... stuck at 7xx.

+++++ additional activity lost when fighting with google authentication,
 after removing sensor, deleting app and data and attempt to start 
App Distribution
Posting this now, more to come.

**Comment by priyonto** [comment] 2023-08-16 20:38
@DG12 Thanks. Would be nice if you could attach a screen record. :)
