### ISSUE TITLE
Alerts are not throttled

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#1122] opened 2022-10-31 19:37 UTC
Please see https://github.com/ruuvi/ruuvi-network-serverless/issues/238, since this is popups in app my guess is that this is iOS and not backend related?

**Comment by priyonto** [comment] 2022-10-31 19:41
Thanks. This seems like an iOS issue. I will work on that.

**Comment by priyonto** [comment] 2022-11-06 20:29
Failed to reproduce it on my end. 

@markoaamunkajo Please check on your end too. Will close if we can't reproduce it.

**Comment by markoaamunkajo** [comment] 2022-11-08 09:30
I cannot reproduce with AppStore version. Moving this to done without findings.

**Closed by markoaamunkajo** 2022-11-08 09:30 UTC
Labels: investigation
