### ISSUE TITLE
Ruuvi Tag AD03 gets data via advertisements but no graph available - 0.7.7(230)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#661] opened 2022-01-10 00:17 UTC
station iOS receives advertisements every few seconds for the last several hours but there is no graph available.
Export contains 2(two) data points from 22-01-08 19:08 and 22-01-09 09:57, 
then beginning at 13:05 datapoints every 5 minutes as expected.

1. Ruuvi AD03 fridge
2. "Date"
3. "2022-01-08 19:08:22"
4. "2022-01-09 09:57:06"
5. "2022-01-09 13:05:03"
6. "2022-01-09 13:10:16"...

![image](https://user-images.githubusercontent.com/2365961/148705902-8b3f74d2-40a6-4445-9744-ab19ec098edb.png)

Station android shows many (many) datapoints over last 12 hours.
webui shows many points as well
![image](https://user-images.githubusercontent.com/2365961/148707020-f34af797-2921-47a8-b67f-311a842ee20e.png)

![image](https://user-images.githubusercontent.com/2365961/148705809-e649d3c6-e7e8-44e0-96d1-243293934c72.png)

**Comment by ojousima** [comment] 2022-01-10 08:27
This is probably caused by legacy code which did not show graphs for non-connectable tags. It made sense before gateway, now not so much

**Comment by priyonto** [comment] 2022-02-15 16:27
@DG12 
This behavior is intentional for the scenarios when a tag is added and not connectable(fetches only advertisements, not heartbits). But, the graph should be available if the sensor is claimed and a gateway is available. Please report back if the chart is not available even after claiming the sensor.

**Comment by DG12** [comment] 2022-02-15 21:45
This seems to be a different behavior than previous.

Consider NO gateway. 
User should still be able to chart multiple sensors and graph them each without connecting to any.
Export should include all datapoints available I.e. those received while sensor was in range of the phone as well as those collected for sensor log via sync to sensor

Please send me your email and I will share some sensors with you  ( DGerman Real-World-Systems com)

I am confused between difference between advertisements and heartbeats. Please clarify/

**Comment by priyonto** [comment] 2022-02-16 14:39
Thank you. There are some technical limitations on the iOS side. But, I believe @laurijamsa is the best person to clarify this issue.

**Comment by DG12** [comment] 2022-02-16 16:26
I don't understand. this worked previously. That is before there was a gateway.

**Comment by markoaamunkajo** [comment] 2022-02-17 03:56
Charts didn't exist for 2.5.9 sensor but I do see csv export has some difficulty collecting all points to report. I have set Settings -> Foreground -> Save Advertisements -> All before testing.

report 1:
[Ruuvi 3C72-220217-1049.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8085420/Ruuvi.3C72-220217-1049.csv)

report 2 (3 minutes later):
[Ruuvi 3C72-220217-1051.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8085424/Ruuvi.3C72-220217-1051.csv)

**Comment by priyonto** [comment] 2022-02-17 07:50
@markoaamunkajo How frequently advertisements are saved in iOS? Are we storing as many data points as android? Also, was this working previously as expected?

**Comment by markoaamunkajo** [comment] 2022-03-04 13:09
FB19 and AD03 (2.5.9) do not !?
 
 @DG12 This can be fixed by updating firmware on sensors.

**Closed by markoaamunkajo** 2022-03-04 13:09 UTC
Labels: bug, 1d

**Comment by DG12** [comment] 2022-03-04 16:37
I really thought that 2.5.9 had graphs before there even was the gateway, 
but perhaps I'm thinking of ruuviCollector & grafana.
I will update firmware and post results.
