### ISSUE TITLE
Tag name should adhere to user specified case - enhancement  0.6.3(1)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#136] opened 2020-10-23 20:39 UTC
If user specified tag name as "MyFavorite" it should not be displayed as "MYFAVORITE"

**Comment by rinat-enikeev** [comment] 2020-11-15 14:42
But this is our UI/UX feature... Not a bug :)

**Comment by DG12** [comment] 2021-01-29 04:40
This prevents using CamelCaseWhenNameing
See also issue #147

**Comment by rinat-enikeev** [comment] 2021-06-09 08:50
https://feedback.ruuvi.com/posts/27/make-tag-names-case-sensitive

closing this issue moving discussion to feedback.

**Closed by rinat-enikeev** 2021-06-09 08:50 UTC

**Comment by DG12** [comment] 2023-04-01 02:16
Finally corrected  3/20/23 :-)
