### ISSUE TITLE
exported CSV is inconsistent with android version - 1.5.8 - minor defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#253] opened 2021-04-22 00:09 UTC
Android:

Timestamp,Temperature (°F), Humidity (%), Pressure (hPa),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Voltage,Movement counter,Measurement sequence number
2021-04-17T13:10:45-0400,53.69,48.31,991.73,-80,0.724,0.672,0.172,2.455,84,15021
+++++++++++++++++++++++++++++++
IOS:

Ruuvi 06DC 
"Date","ISO8601","Temperature (°F)","Humidity (%)","Pressure (hPa)",Acceleration X,Acceleration Y,Acceleration Z,"Voltage (V)","Movement Counter", "Measurement Sequence Number","TX Power"
"2021-04-20 17:27:31",2021-04-20T21:27:31.878Z,73.07,38.99,995.43,0.056,0.004,1.011,2.685,64,58645,4
++++++++++++++++++++++++++++++
IOS data includes device name  as first row - good
IOS Date column is in quotes - is that necessary?
IOS includes ISO8601 date-time - good
Android includes RSSI - good
IOS SOME headers include quotes - not so good (better if they all did ?)
IOS includes TX power -  why?

FIle name has spaces replaced with underscores ("_") - good

**Comment by rinat-enikeev** [comment] 2021-06-09 08:17
unify exported file with Android

**Comment by markoaamunkajo** [comment] 2021-06-09 12:57
https://github.com/ruuvi/com.ruuvi.station/issues/353 for Android

**Comment by markoaamunkajo** [comment] 2022-02-10 12:48
Minor difference:

Android report has RSSI
Naming should be name_yyyymmdd-hhmm

**Comment by markoaamunkajo** [comment] 2022-02-18 05:20
0.7.7(248) iPhone7, iOS 14.8

Csv export gets stuck in this screen, no way to exit but to kill app.

![IMG_8198](https://user-images.githubusercontent.com/50437378/154622338-4a560226-027e-4bd0-a13d-a2d0c7cd2748.PNG)

**Comment by markoaamunkajo** [comment] 2022-03-03 03:17
Build 0.7.7(249)

Export now successful but looks like local sensor with latest firmware is missing a lot of data compared to same sensor on Android. These measurements were GATT synced on iOS.



Left: iOS Right: Android
![Screenshot 2022-03-03 at 10 08 37](https://user-images.githubusercontent.com/50437378/156489302-df4389eb-9037-4c2d-8838-5fb0d9efb765.png)

**Comment by priyonto** [comment] 2022-03-03 17:58
@markoaamunkajo This is happening on the Gatt sync only. And it's reproducible on the app store build as well. I am wondering why. I will investigate it more.

**Comment by priyonto** [comment] 2022-03-03 18:41
I did a GATT sync on both iOS and Android apps on the same sensor and noticed that the records received from the GATT are missing those values on both apps. I was not aware of this earlier but it seems like we are not receiving these values from the GATT. 

[Android.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8180284/Android.csv)
[iOS.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8180285/iOS.csv)

**Comment by markoaamunkajo** [comment] 2022-03-04 12:08
@priyonto I'm guessing should consult with @io53 how this can be possible.

**Comment by priyonto** [comment] 2022-03-04 12:12
@markoaamunkajo These values are not received from the GATT. @andreevdenis confirmed this yesterday. The only difference I can find in iOS and Android app is - Android app is showing '0' for no values and iOS is showing '-'.

**Comment by markoaamunkajo** [comment] 2022-03-04 13:30
OK then it's a known feature, will close this issue

**Closed by markoaamunkajo** 2022-03-04 13:30 UTC
Labels: bug, enhancement
