### ISSUE TITLE
Attempt to share with no wifi/cell connection spins indefinitely 2.0.0 (354) bug 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1338] opened 2023-03-02 17:10 UTC
If iPhone is out of range of wifi with no cellular access, 
Attempt to share spins indefinitely.
Must kill app.

**Comment by markoaamunkajo** [comment] 2023-03-03 01:22
Closing as duplicate of https://github.com/ruuvi/com.ruuvi.station.ios/issues/1336

**Closed by markoaamunkajo** 2023-03-03 01:22 UTC
