### ISSUE TITLE
Live sensor data flickers and settings menu gets stuck

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#618] opened 2021-12-06 17:49 UTC
This is a user report with limited information. Seems that live data is jumping between old and new results (see the movement counter and updated info). Also settings page gets stuck when browsing.

Device: iPhone 12 Pro Max
OS: iOS 15.1.1
App: Ruuvi Station 0.7.6(206)

See the videos:

https://user-images.githubusercontent.com/1311912/144895275-e31f2979-d55b-4f9c-8287-0ca5be1298ba.mov

https://user-images.githubusercontent.com/1311912/144895297-6362101e-9833-4f2c-8827-8f9403f5a99d.mov

EDIT: The user removed and reinstalled the app and added the sensor again and now all works ok.

**Comment by priyonto** [comment] 2022-01-11 11:16
I was unable to reproduce these issues after several tries. Tried logging out/in back and forth, randomly using the app, trying to go to background-foreground back and forth as we have very limited information on this. The app seems to be working as expected without getting stuck of fructuated values. 

Device:
iPhone 11 Pro Max iOS 15.1
Simulator:
iPhone 13 iOS 15.0

**Comment by priyonto** [comment] 2022-01-14 10:50
@markoaamunkajo May I ask you to try to reproduce this, please? I tried several times and could not. Thank you.

**Comment by markoaamunkajo** [comment] 2022-01-14 11:50
Cannot reproduce. I have a feeling that iPhone 11 Pro Max has been problematic with some other case too, very specific issue regarding this model.

**Comment by priyonto** [comment] 2022-01-14 11:51
I have the iPhone 11 Pro Max, and could not produce this issue on my device.

**Comment by markoaamunkajo** [comment] 2022-01-17 02:01
Let's close this case because user issue has been resolved and we cannot replicate.

**Closed by markoaamunkajo** 2022-01-17 02:01 UTC
Labels: bug
