### ISSUE TITLE
firmware update: doesn't report but said  v3.28.0 1.1.1(291) - outlier

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#906] opened 2022-05-06 12:03 UTC
EC0F Sensor Settings Current Version says v3.28.0 but
tap on update reports in 3 seconds
 "Your sensor doesn't report its current firmware version"

**Comment by priyonto** [comment] 2022-06-15 15:10
@DG12 Could you please try removing and re-adding the sensor? In my testing I couldn't reproduce it yet on my end. I tried on tags with new and very old firmware.

**Comment by priyonto** [comment] 2022-06-17 11:45
I was unable to reproduce this issue. Another reason can be when tapping on the update the BT communication did not took place properly. I am handing it over to our QA @markoaamunkajo to test more.

**Comment by markoaamunkajo** [comment] 2022-06-21 09:52
@priyonto this happens when I'm already in connected mode on another iOS device and checking the Firmware Update page on the device that is not connected.

**Comment by priyonto** [comment] 2022-06-21 09:54
Thank you @markoaamunkajo

That's understandable. Probably shouldn't allow checking(disable the button or so?) firmware in such scenarios?

**Comment by priyonto** [comment] 2022-06-21 12:18
Thanks. Please do update here once you are able to reproduce it. :)

**Comment by DG12** [comment] 2022-06-21 12:19
Is there an easy way to see if RuuviTag is connected to a mobil?

**Comment by DG12** [comment] 2022-06-21 12:24
I guess using the app on iOS,  battery dead on android, will charge

**Comment by markoaamunkajo** [comment] 2022-06-29 10:56
Closing this card for now, nothing to do.

**Closed by markoaamunkajo** 2022-06-29 10:56 UTC
Labels: investigation
