### ISSUE TITLE
Chart missing "latest" value - defect - 2412011902 + 2412072018

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2201] opened 2024-12-01 21:41 UTC
Fresh install. Many sensors set up from gateway.
Min,max,avg show but no latest on any sensor
![ruuvi-no-latest copy](https://github.com/user-attachments/assets/ce1bc28a-0a95-4238-9fab-c86dde039b63)
15 minutes later no better.
shutdown / restart no better.

**Comment by markoaamunkajo** [comment] 2024-12-04 04:41
I have tried multiple different possibilities here and have not managed to reproduce this issue.

**Comment by DG12** [comment] 2024-12-08 00:14
@markoaamunkajo Please post a chart from an iPhone.

**Comment by markoaamunkajo** [comment] 2024-12-16 06:14
https://github.com/user-attachments/assets/d2340557-6093-4036-9398-f6f33a53ad37

Tested again with 2412072018, clean install, sign in, test themes, it will not happen for me.
@DG12 What device are you checking this with? Is it happening consistently to you?

**Comment by markoaamunkajo** [comment] 2024-12-19 01:19
Still not able to reproduce this one.

**Comment by markoaamunkajo** [comment] 2024-12-23 05:04
This must be related to some internal version, I haven't spotted it, so I will close this card and if it is seen again, will be happy to reopen and investigate.

**Closed by markoaamunkajo** 2024-12-23 05:04 UTC
Labels: bug

**Comment by DG12** [comment] 2025-01-07 21:42
looks OK now 2.13.0(2412121751)
